kind: pipeline
type: docker
name: default
platform:
  os: linux
  arch: arm64
steps:
- name: arm64-build
  image: plugins/docker
  settings:
    repo: gsp8181/protonmail-bridge
    tags: latest
    username: gsp8181
    dockerfile: build/Dockerfile
    password:
      from_secret: docker_password
